language: d

os:
  - linux
  - osx

d:
  # support 3 versions
  - dmd
  - dmd-2.081.1
  - dmd-2.080.0
  - dmd-2.079.0
  - ldc
  - ldc-1.10.0
  - ldc-1.9.0
  - ldc-1.8.0

script:
  - dub test -b unittest-cov

after_success:
 - bash <(curl -s https://codecov.io/bash)

test:
  dub test