language: d

os:
  - linux
  - osx

d:
  # support 3 versions
  - dmd
  - dmd-2.084.0
  - dmd-2.083.1
  - dmd-2.082.1
  - ldc
  - ldc-1.13.0
  - ldc-1.12.0
  - ldc-1.11.0

script:
  - dub test -b unittest-cov

after_success:
 - bash <(curl -s https://codecov.io/bash)

test:
  dub test